### ISSUE TITLE
My skip links won't work

### ISSUE THREAD

**Issue by nadim944** [nadim944/dsn1676-term-project#1]
Hi Thomas hope your'e doing well, iv'e been having an issue with my skip links for some reason. They don't show up when my nav is closed. It seems like its connected to my nav. I was wondering how I could fix this issue.

Thanks

 http://nadim944.github.io/dsn1676-term-project/

@thomasjbradley

**Comment by thomasjbradley** [comment]
Add a `z-index` to the `skip-links a` to force them in front.
